name: Docker Image CI
on:
   push:
     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get latest release version of dnsmasq
      run: RELEASE_VERSION=$(curl -s http://thekelleys.org.uk/dnsmasq/ | grep -oP '(?<=LATEST_IS_)[0-9\.]*?(?=\")') && echo "::set-env name=RELEASE_VERSION::$RELEASE_VERSION"

    - name: Login to github container registry
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u pujan14 --password-stdin

    - name: Build the Docker distroless image
      run: docker build . --file Dockerfile --build-arg VERSION=$RELEASE_VERSION
          --tag ghcr.io/pujan14/dnsmasq:${{ github.sha }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/pujan14/dnsmasq:${{ github.sha }}'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Build the Docker alpine image
      run: docker build . --file alpine.Dockerfile
          --tag ghcr.io/pujan14/dnsmasq:latest-alpine

    - name: Push the Docker image
      run: docker push ghcr.io/pujan14/dnsmasq
