name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name : Login to github container registry
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u pujan14 --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/pujan14/dnsmasq:$GITHUB_SHA

    - name: Retag the image
      run: docker tag ghcr.io/pujan14/dnsmasq:$GITHUB_SHA ghcr.io/pujan14/dnsmasq:latest

    - name: Push the Docker image
      run: docker push ghcr.io/pujan14/dnsmasq
