name: Docker Image CI
on:
  push:
    branches-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get latest release version of dnsmasq
      run: RELEASE_VERSION=$(curl -s http://thekelleys.org.uk/dnsmasq/ | grep -oP '(?<=LATEST_IS_)[0-9\.]*?(?=\")') && echo "::set-env name=RELEASE_VERSION::$RELEASE_VERSION"

    - name: Get latest version build with this repo
      run: BUILD_VERSION=$(curl https://ghcr.io/v2/pujan14/dnsmasq/tags/list -s | jq .tags | grep -oP "[0-9\.]*" | sort -V | tail -n 1)  && echo "::set-env name=BUILD_VERSION::$BUILD_VERSION"

    - name: Login to github container registry
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u pujan14 --password-stdin

    - name: Create folder for sarif reports
      run: mkdir sarif

    - name: Build the Docker distroless image
      run: docker build . --file Dockerfile --build-arg VERSION=$RELEASE_VERSION
          --tag ghcr.io/pujan14/dnsmasq:$RELEASE_VERSION
          --tag ghcr.io/pujan14/dnsmasq:latest
      if: env.BUILD_VERSION != env.RELEASE_VERSION

    - name: Pull the Docker distroless image
      run: docker pull ghcr.io/pujan14/dnsmasq:$RELEASE_VERSION
      if: env.BUILD_VERSION == env.RELEASE_VERSION

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "ghcr.io/pujan14/dnsmasq:$RELEASE_VERSION"
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'

    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: "ghcr.io/pujan14/dnsmasq:$RELEASE_VERSION"
        args: --file=Dockerfile

    - name: Run the anchore scan action
      uses: anchore/scan-action@v2
      with:
        image: "ghcr.io/pujan14/dnsmasq:$RELEASE_VERSION"
        acs-report-enable: true

    - name: Move sarif scan reports
      run: mv snyk.sarif sarif/snyk-distroless.sarif && mv result.sarif sarif/anchore-distroless.sarif || true

    - name: Upload sarif scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'sarif'

    - uses: actions/upload-artifact@v2
      with:
        name: sarif-reports
        path: sarif/

    - name: Push the Docker image
      run: docker push ghcr.io/pujan14/dnsmasq
      if: env.BUILD_VERSION != env.RELEASE_VERSION
